import Mathlib


-- syntax of first-order set theory

/-- Terms of the language of set theory. -/
inductive Term : Type
  | var : Nat → Term
deriving DecidableEq, Repr

/-- First-order formulas for set theory. -/
inductive Formula : Type
  | fals : Formula
  | eq : Term → Term → Formula
  | mem : Term → Term → Formula
  | imp : Formula → Formula → Formula
  | neg : Formula → Formula
  | all : Formula → Formula
deriving DecidableEq, Repr

-- notations for readability

/-- Notations for falsity. -/
notation "⊥₀" => Formula.fals
/-- Notations for equality. -/
infix:50 " =₀ " => Formula.eq
/-- Notations for membership. -/
infix:50 " ∈₀ " => Formula.mem
/-- Notations for implication. -/
infixr:60 " →₀ " => Formula.imp
/-- Notations for negation. -/
prefix:70 "¬₀ " => Formula.neg
/-- Notations for universal quantifier. -/
notation "∀₀ " φ => Formula.all φ

/-- Shorthand for variables. -/
def v (n : Nat) : Term := Term.var n


-- derived logical connectives

namespace Formula

/-- Definition of conjunction. -/
def and (φ ψ : Formula) : Formula :=
  ¬₀ (φ →₀ ¬₀ ψ)

/-- Definition of disjunction. -/
def or (φ ψ : Formula) : Formula :=
  (¬₀ φ) →₀ ψ

/-- Definition of biconditional. -/
def iff (φ ψ : Formula) : Formula :=
  and (φ →₀ ψ) (ψ →₀ φ)

/-- Definition of existential quantifier. -/
def ex (φ : Formula) : Formula :=
  ¬₀ (∀₀ (¬₀ φ))

end Formula

-- additional notations

/-- Notations for conjunction. -/
infixr:55 " ∧₀ " => Formula.and
/-- Notations for disjunction. -/
infixr:50 " ∨₀ " => Formula.or
/-- Notations for biconditional. -/
infix:40 " ↔₀ " => Formula.iff
/-- Notations for existential quantifier. -/
notation "∃₀ " φ => Formula.ex φ


-- lifting and substitution

/-- Lift variables greater than or equal to `k` by one. -/
def liftTerm : Nat → Term → Term
  | k, Term.var n => Term.var (if k ≤ n then n + 1 else n)

/-- Substitute the term `s` for variable `0`. -/
def substTerm (s : Term) : Term → Term
  | Term.var 0 => s
  | Term.var (n+1) => Term.var n

/-- Lift free variables in a formula. -/
def lift : Nat → Formula → Formula
  | _, Formula.fals => ⊥₀
  | k, Formula.eq t₁ t₂ => liftTerm k t₁ =₀ liftTerm k t₂
  | k, Formula.mem t₁ t₂ => liftTerm k t₁ ∈₀ liftTerm k t₂
  | k, Formula.imp φ ψ => lift k φ →₀ lift k ψ
  | k, Formula.neg φ => ¬₀ (lift k φ)
  | k, Formula.all φ => ∀₀ (lift (k + 1) φ)

/-- Substitute the term `s`
for free variable `0` in a formula. -/
def subst : Term → Formula → Formula
  | _, Formula.fals => ⊥₀
  | s, Formula.eq t₁ t₂ => substTerm s t₁ =₀ substTerm s t₂
  | s, Formula.mem t₁ t₂ => substTerm s t₁ ∈₀ substTerm s t₂
  | s, Formula.imp φ ψ => subst s φ →₀ subst s ψ
  | s, Formula.neg φ => ¬₀ (subst s φ)
  | s, Formula.all φ => ∀₀ (subst (liftTerm 0 s) φ)


-- axioms for set theory

/-- Extensionality. -/
def extensionality : Formula :=
  ∀₀ ∀₀ (
    (∀₀ ((v 0 ∈₀ v 2) ↔₀ (v 0 ∈₀ v 1)))
      →₀
    (v 1 =₀ v 0)
  )

/-- Empty set. -/
def empty : Formula :=
  ∃₀ (∀₀ (¬₀ (v 0 ∈₀ v 1)))

/-- Pairing. -/
def pairing : Formula :=
  ∀₀ ∀₀ (
    ∃₀ (
      ∀₀ (
        (v 0 ∈₀ v 3)
          ↔₀
        ((v 0 =₀ v 2) ∨₀ (v 0 =₀ v 1))
      )
    )
  )

/-- Union. -/
def union : Formula :=
  ∀₀ (
    ∃₀ (
      ∀₀ (
        (v 0 ∈₀ v 2)
          ↔₀
        ∃₀ (
          (v 0 ∈₀ v 3) ∧₀ (v 1 ∈₀ v 0)
        )
      )
    )
  )

/-- Power set. -/
def powerset : Formula :=
  ∀₀ (
    ∃₀ (
      ∀₀ (
        (v 0 ∈₀ v 2)
          ↔₀
        ∀₀ (
          (v 0 ∈₀ v 1) →₀ (v 0 ∈₀ v 3)
        )
      )
    )
  )

/-- Foundation. -/
def foundation : Formula :=
  ∀₀ (
    (∃₀ (v 0 ∈₀ v 1))
      →₀
    ∃₀ (
      (v 0 ∈₀ v 1)
        ∧₀
      ∀₀ (
        (v 0 ∈₀ v 1)
          →₀
        ¬₀ (v 0 ∈₀ v 2)
      )
    )
  )

/-- Infinity. -/
def infinity : Formula :=
  ∃₀ (
    (∃₀ (v 0 ∈₀ v 1))
      ∧₀
    ∀₀ (
      (v 0 ∈₀ v 1)
        →₀
      ∃₀ (
        (v 0 ∈₀ v 2) ∧₀ (v 1 ∈₀ v 0)
      )
    )
  )


-- defining theory

/-- A first-order theory is just a set of formulas. -/
abbrev Theory := Set Formula

/-- The fixed axioms of ZF currently included. -/
def ZF : Theory :=
  {φ | φ = extensionality
    ∨ φ = empty
    ∨ φ = pairing
    ∨ φ = union
    ∨ φ = powerset
    ∨ φ = foundation
    ∨ φ = infinity}


-- Separation schema

/-- Separation schema generated by a formula `φ`. -/
def separation (φ : Formula) : Formula :=
  ∀₀ (
    ∃₀ (
      ∀₀ (
        (v 0 ∈₀ v 1)
          ↔₀
        ((v 0 ∈₀ v 2) ∧₀ (lift 2 φ))
      )
    )
  )

/-- The Separation instances belonging to the schema. -/
def SeparationTheory : Theory :=
  {ψ | ∃ φ : Formula, ψ = separation φ}


-- Replacement schema

/-- Functional condition for a formula `φ`. -/
def functional (φ : Formula) : Formula :=
  ∀₀ (
    ∀₀ (
      ∀₀ (
        ((lift 2 φ) ∧₀ (lift 1 φ))
          →₀
        (v 1 =₀ v 0)
      )
    )
  )

/-- Replacement schema generated by a formula `φ`. -/
def replacement (φ : Formula) : Formula :=
  functional φ
    →₀
  ∀₀ (
    ∃₀ (
      ∀₀ (
        (v 0 ∈₀ v 1)
          ↔₀
        ∃₀ (
          (v 0 ∈₀ v 3) ∧₀ (lift 2 φ)
        )
      )
    )
  )

/-- The Replacement instances belonging to the schema. -/
def ReplacementTheory : Theory :=
  {ψ | ∃ φ : Formula, ψ = replacement φ}


-- the theory ZF

/-- ZF with Separation and Replacement. -/
def ZF_full : Theory :=
  ZF ∪ SeparationTheory ∪ ReplacementTheory


-- Axiom of Choice

/-- Every member of `x` is nonempty. -/
def nonemptyMembers : Formula :=
  ∀₀ (
    (v 0 ∈₀ v 1)
      →₀
    ∃₀ (v 0 ∈₀ v 1)
  )

/-- Members of `x` are pairwise disjoint. -/
def pairwiseDisjointMembers : Formula :=
  ∀₀ (
    ∀₀ (
      (((v 1 ∈₀ v 2) ∧₀ (v 0 ∈₀ v 2))
          ∧₀
        ∃₀ ((v 0 ∈₀ v 2) ∧₀ (v 0 ∈₀ v 1)))
        →₀
      (v 1 =₀ v 0)
    )
  )

/-- `c` is a choice set for `x`:
for every `y ∈ x`, there exists exactly one
`z` such that `z ∈ y` and `z ∈ c`. -/
def choiceSetFor : Formula :=
  ∀₀ (
    (v 0 ∈₀ v 2)
      →₀
    ∃₀ (
      (v 0 ∈₀ v 1)
        ∧₀
      ((v 0 ∈₀ v 2)
        ∧₀
       ∀₀ (
         (((v 0 ∈₀ v 2) ∧₀ (v 0 ∈₀ v 3))
            →₀
          (v 0 =₀ v 1))
       ))
    )
  )

/-- Axiom of Choice in the pairwise-disjoint family form. -/
def choice : Formula :=
  ∀₀ (
    ((nonemptyMembers ∧₀ pairwiseDisjointMembers)
      →₀
     ∃₀ choiceSetFor)
  )

/-- ZFC = ZF + Choice. -/
def ZFC : Theory :=
  ZF_full ∪ {φ | φ = choice}


#lint
